# coding: utf-8

"""
    Phishing Hunter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from phishing_hunter.paths.observation.get import GetObservations
from phishing_hunter.paths.observation_add.post import PostObservationAdd
from phishing_hunter.paths.observation_remove.post import PostObservationRemove


class ObservationApi(
    GetObservations,
    PostObservationAdd,
    PostObservationRemove,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
