# coding: utf-8

"""
    Phishing Hunter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from phishing_hunter.paths.scanner.get import GetScanner
from phishing_hunter.paths.scanner_add.post import PostScannerAdd
from phishing_hunter.paths.scanner_remove.post import PostScannerRemove


class ScannerApi(
    GetScanner,
    PostScannerAdd,
    PostScannerRemove,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
