# coding: utf-8

"""
    Phishing Hunter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from phishing_hunter.paths.apikeys.get import GetApikeys
from phishing_hunter.paths.notify.get import GetNotifySlack
from phishing_hunter.paths.apikeys.post import PostApikeys
from phishing_hunter.paths.notify.post import PostNotifySlack


class SettingsApi(
    GetApikeys,
    GetNotifySlack,
    PostApikeys,
    PostNotifySlack,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
