# coding: utf-8

"""
    Phishing Hunter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from phishing_hunter.paths.apikey.get import GetApikey
from phishing_hunter.paths.users_info.get import GetUsersInfo
from phishing_hunter.paths.apikey_create.post import PostApikeyCreate
from phishing_hunter.paths.apikey_delete.post import PostApikeyDelete


class UserApi(
    GetApikey,
    GetUsersInfo,
    PostApikeyCreate,
    PostApikeyDelete,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
