/**
 * Phishing Hunter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetApikeys200ResponseApiKeys from './GetApikeys200ResponseApiKeys';

/**
 * The GetApikeys200Response model module.
 * @module model/GetApikeys200Response
 * @version 1.0
 */
class GetApikeys200Response {
    /**
     * Constructs a new <code>GetApikeys200Response</code>.
     * @alias module:model/GetApikeys200Response
     */
    constructor() { 
        
        GetApikeys200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetApikeys200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetApikeys200Response} obj Optional instance to populate.
     * @return {module:model/GetApikeys200Response} The populated <code>GetApikeys200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetApikeys200Response();

            if (data.hasOwnProperty('api_keys')) {
                obj['api_keys'] = GetApikeys200ResponseApiKeys.constructFromObject(data['api_keys']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetApikeys200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetApikeys200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `api_keys`
        if (data['api_keys']) { // data not null
          GetApikeys200ResponseApiKeys.validateJSON(data['api_keys']);
        }

        return true;
    }


}



/**
 * @member {module:model/GetApikeys200ResponseApiKeys} api_keys
 */
GetApikeys200Response.prototype['api_keys'] = undefined;






export default GetApikeys200Response;

