/**
 * Phishing Hunter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetHunting200ResponseKeywords model module.
 * @module model/GetHunting200ResponseKeywords
 * @version 1.0
 */
class GetHunting200ResponseKeywords {
    /**
     * Constructs a new <code>GetHunting200ResponseKeywords</code>.
     * @alias module:model/GetHunting200ResponseKeywords
     */
    constructor() { 
        
        GetHunting200ResponseKeywords.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetHunting200ResponseKeywords</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetHunting200ResponseKeywords} obj Optional instance to populate.
     * @return {module:model/GetHunting200ResponseKeywords} The populated <code>GetHunting200ResponseKeywords</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetHunting200ResponseKeywords();

            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], ['String']);
            }
            if (data.hasOwnProperty('dom')) {
                obj['dom'] = ApiClient.convertToType(data['dom'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetHunting200ResponseKeywords</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetHunting200ResponseKeywords</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['domain'])) {
            throw new Error("Expected the field `domain` to be an array in the JSON data but got " + data['domain']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['dom'])) {
            throw new Error("Expected the field `dom` to be an array in the JSON data but got " + data['dom']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} domain
 */
GetHunting200ResponseKeywords.prototype['domain'] = undefined;

/**
 * @member {Array.<String>} dom
 */
GetHunting200ResponseKeywords.prototype['dom'] = undefined;






export default GetHunting200ResponseKeywords;

