/**
 * Phishing Hunter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetHunting200ResponseKeywords from './GetHunting200ResponseKeywords';

/**
 * The GetHunting200Response model module.
 * @module model/GetHunting200Response
 * @version 1.0
 */
class GetHunting200Response {
    /**
     * Constructs a new <code>GetHunting200Response</code>.
     * @alias module:model/GetHunting200Response
     */
    constructor() { 
        
        GetHunting200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetHunting200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetHunting200Response} obj Optional instance to populate.
     * @return {module:model/GetHunting200Response} The populated <code>GetHunting200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetHunting200Response();

            if (data.hasOwnProperty('keywords')) {
                obj['keywords'] = GetHunting200ResponseKeywords.constructFromObject(data['keywords']);
            }
            if (data.hasOwnProperty('target_score')) {
                obj['target_score'] = ApiClient.convertToType(data['target_score'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetHunting200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetHunting200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `keywords`
        if (data['keywords']) { // data not null
          GetHunting200ResponseKeywords.validateJSON(data['keywords']);
        }

        return true;
    }


}



/**
 * @member {module:model/GetHunting200ResponseKeywords} keywords
 */
GetHunting200Response.prototype['keywords'] = undefined;

/**
 * @member {Number} target_score
 */
GetHunting200Response.prototype['target_score'] = undefined;






export default GetHunting200Response;

