/**
 * Phishing Hunter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetNotifySlack200ResponseHunting from './GetNotifySlack200ResponseHunting';

/**
 * The GetNotifySlack200Response model module.
 * @module model/GetNotifySlack200Response
 * @version 1.0
 */
class GetNotifySlack200Response {
    /**
     * Constructs a new <code>GetNotifySlack200Response</code>.
     * @alias module:model/GetNotifySlack200Response
     */
    constructor() { 
        
        GetNotifySlack200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetNotifySlack200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetNotifySlack200Response} obj Optional instance to populate.
     * @return {module:model/GetNotifySlack200Response} The populated <code>GetNotifySlack200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetNotifySlack200Response();

            if (data.hasOwnProperty('hunting')) {
                obj['hunting'] = GetNotifySlack200ResponseHunting.constructFromObject(data['hunting']);
            }
            if (data.hasOwnProperty('observation')) {
                obj['observation'] = GetNotifySlack200ResponseHunting.constructFromObject(data['observation']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetNotifySlack200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetNotifySlack200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `hunting`
        if (data['hunting']) { // data not null
          GetNotifySlack200ResponseHunting.validateJSON(data['hunting']);
        }
        // validate the optional field `observation`
        if (data['observation']) { // data not null
          GetNotifySlack200ResponseHunting.validateJSON(data['observation']);
        }

        return true;
    }


}



/**
 * @member {module:model/GetNotifySlack200ResponseHunting} hunting
 */
GetNotifySlack200Response.prototype['hunting'] = undefined;

/**
 * @member {module:model/GetNotifySlack200ResponseHunting} observation
 */
GetNotifySlack200Response.prototype['observation'] = undefined;






export default GetNotifySlack200Response;

