/**
 * Phishing Hunter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetUsersInfo200ResponseQuota from './GetUsersInfo200ResponseQuota';

/**
 * The GetUsersInfo200Response model module.
 * @module model/GetUsersInfo200Response
 * @version 1.0
 */
class GetUsersInfo200Response {
    /**
     * Constructs a new <code>GetUsersInfo200Response</code>.
     * @alias module:model/GetUsersInfo200Response
     */
    constructor() { 
        
        GetUsersInfo200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetUsersInfo200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetUsersInfo200Response} obj Optional instance to populate.
     * @return {module:model/GetUsersInfo200Response} The populated <code>GetUsersInfo200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetUsersInfo200Response();

            if (data.hasOwnProperty('quota')) {
                obj['quota'] = GetUsersInfo200ResponseQuota.constructFromObject(data['quota']);
            }
            if (data.hasOwnProperty('user_plan')) {
                obj['user_plan'] = ApiClient.convertToType(data['user_plan'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetUsersInfo200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetUsersInfo200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `quota`
        if (data['quota']) { // data not null
          GetUsersInfo200ResponseQuota.validateJSON(data['quota']);
        }
        // ensure the json data is a string
        if (data['user_plan'] && !(typeof data['user_plan'] === 'string' || data['user_plan'] instanceof String)) {
            throw new Error("Expected the field `user_plan` to be a primitive type in the JSON string but got " + data['user_plan']);
        }

        return true;
    }


}



/**
 * @member {module:model/GetUsersInfo200ResponseQuota} quota
 */
GetUsersInfo200Response.prototype['quota'] = undefined;

/**
 * @member {String} user_plan
 */
GetUsersInfo200Response.prototype['user_plan'] = undefined;






export default GetUsersInfo200Response;

