/**
 * Phishing Hunter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetUsersInfo200ResponseQuota model module.
 * @module model/GetUsersInfo200ResponseQuota
 * @version 1.0
 */
class GetUsersInfo200ResponseQuota {
    /**
     * Constructs a new <code>GetUsersInfo200ResponseQuota</code>.
     * @alias module:model/GetUsersInfo200ResponseQuota
     */
    constructor() { 
        
        GetUsersInfo200ResponseQuota.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetUsersInfo200ResponseQuota</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetUsersInfo200ResponseQuota} obj Optional instance to populate.
     * @return {module:model/GetUsersInfo200ResponseQuota} The populated <code>GetUsersInfo200ResponseQuota</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetUsersInfo200ResponseQuota();

            if (data.hasOwnProperty('domain_keywords')) {
                obj['domain_keywords'] = ApiClient.convertToType(data['domain_keywords'], 'Number');
            }
            if (data.hasOwnProperty('observations')) {
                obj['observations'] = ApiClient.convertToType(data['observations'], 'Number');
            }
            if (data.hasOwnProperty('scanner')) {
                obj['scanner'] = ApiClient.convertToType(data['scanner'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetUsersInfo200ResponseQuota</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetUsersInfo200ResponseQuota</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} domain_keywords
 */
GetUsersInfo200ResponseQuota.prototype['domain_keywords'] = undefined;

/**
 * @member {Number} observations
 */
GetUsersInfo200ResponseQuota.prototype['observations'] = undefined;

/**
 * @member {Number} scanner
 */
GetUsersInfo200ResponseQuota.prototype['scanner'] = undefined;






export default GetUsersInfo200ResponseQuota;

