/**
 * Phishing Hunter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostObservationAddRequestApiConfigUrlscan from './PostObservationAddRequestApiConfigUrlscan';

/**
 * The PostObservationAddRequestApiConfig model module.
 * @module model/PostObservationAddRequestApiConfig
 * @version 1.0
 */
class PostObservationAddRequestApiConfig {
    /**
     * Constructs a new <code>PostObservationAddRequestApiConfig</code>.
     * @alias module:model/PostObservationAddRequestApiConfig
     */
    constructor() { 
        
        PostObservationAddRequestApiConfig.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostObservationAddRequestApiConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostObservationAddRequestApiConfig} obj Optional instance to populate.
     * @return {module:model/PostObservationAddRequestApiConfig} The populated <code>PostObservationAddRequestApiConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostObservationAddRequestApiConfig();

            if (data.hasOwnProperty('urlscan')) {
                obj['urlscan'] = PostObservationAddRequestApiConfigUrlscan.constructFromObject(data['urlscan']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostObservationAddRequestApiConfig</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostObservationAddRequestApiConfig</code>.
     */
    static validateJSON(data) {
        // validate the optional field `urlscan`
        if (data['urlscan']) { // data not null
          PostObservationAddRequestApiConfigUrlscan.validateJSON(data['urlscan']);
        }

        return true;
    }


}



/**
 * @member {module:model/PostObservationAddRequestApiConfigUrlscan} urlscan
 */
PostObservationAddRequestApiConfig.prototype['urlscan'] = undefined;






export default PostObservationAddRequestApiConfig;

