/**
 * Phishing Hunter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostObservationAddRequestApiConfig from './PostObservationAddRequestApiConfig';

/**
 * The PostObservationAddRequest model module.
 * @module model/PostObservationAddRequest
 * @version 1.0
 */
class PostObservationAddRequest {
    /**
     * Constructs a new <code>PostObservationAddRequest</code>.
     * @alias module:model/PostObservationAddRequest
     */
    constructor() { 
        
        PostObservationAddRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostObservationAddRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostObservationAddRequest} obj Optional instance to populate.
     * @return {module:model/PostObservationAddRequest} The populated <code>PostObservationAddRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostObservationAddRequest();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('interval')) {
                obj['interval'] = ApiClient.convertToType(data['interval'], 'String');
            }
            if (data.hasOwnProperty('period')) {
                obj['period'] = ApiClient.convertToType(data['period'], 'Number');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('expire')) {
                obj['expire'] = ApiClient.convertToType(data['expire'], 'Number');
            }
            if (data.hasOwnProperty('api_config')) {
                obj['api_config'] = PostObservationAddRequestApiConfig.constructFromObject(data['api_config']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostObservationAddRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostObservationAddRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['interval'] && !(typeof data['interval'] === 'string' || data['interval'] instanceof String)) {
            throw new Error("Expected the field `interval` to be a primitive type in the JSON string but got " + data['interval']);
        }
        // ensure the json data is a string
        if (data['comment'] && !(typeof data['comment'] === 'string' || data['comment'] instanceof String)) {
            throw new Error("Expected the field `comment` to be a primitive type in the JSON string but got " + data['comment']);
        }
        // validate the optional field `api_config`
        if (data['api_config']) { // data not null
          PostObservationAddRequestApiConfig.validateJSON(data['api_config']);
        }

        return true;
    }


}



/**
 * @member {String} url
 */
PostObservationAddRequest.prototype['url'] = undefined;

/**
 * @member {String} interval
 */
PostObservationAddRequest.prototype['interval'] = undefined;

/**
 * @member {Number} period
 */
PostObservationAddRequest.prototype['period'] = undefined;

/**
 * @member {String} comment
 */
PostObservationAddRequest.prototype['comment'] = undefined;

/**
 * @member {Number} expire
 */
PostObservationAddRequest.prototype['expire'] = undefined;

/**
 * @member {module:model/PostObservationAddRequestApiConfig} api_config
 */
PostObservationAddRequest.prototype['api_config'] = undefined;






export default PostObservationAddRequest;

