/*
Phishing Hunter API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phishing_hunter

import (
	"encoding/json"
)

// checks if the PostApikeyDelete200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostApikeyDelete200Response{}

// PostApikeyDelete200Response struct for PostApikeyDelete200Response
type PostApikeyDelete200Response struct {
	Message *string `json:"message,omitempty"`
}

// NewPostApikeyDelete200Response instantiates a new PostApikeyDelete200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostApikeyDelete200Response() *PostApikeyDelete200Response {
	this := PostApikeyDelete200Response{}
	return &this
}

// NewPostApikeyDelete200ResponseWithDefaults instantiates a new PostApikeyDelete200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostApikeyDelete200ResponseWithDefaults() *PostApikeyDelete200Response {
	this := PostApikeyDelete200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *PostApikeyDelete200Response) GetMessage() string {
	if o == nil || isNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostApikeyDelete200Response) GetMessageOk() (*string, bool) {
	if o == nil || isNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *PostApikeyDelete200Response) HasMessage() bool {
	if o != nil && !isNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *PostApikeyDelete200Response) SetMessage(v string) {
	o.Message = &v
}

func (o PostApikeyDelete200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostApikeyDelete200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullablePostApikeyDelete200Response struct {
	value *PostApikeyDelete200Response
	isSet bool
}

func (v NullablePostApikeyDelete200Response) Get() *PostApikeyDelete200Response {
	return v.value
}

func (v *NullablePostApikeyDelete200Response) Set(val *PostApikeyDelete200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostApikeyDelete200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostApikeyDelete200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostApikeyDelete200Response(val *PostApikeyDelete200Response) *NullablePostApikeyDelete200Response {
	return &NullablePostApikeyDelete200Response{value: val, isSet: true}
}

func (v NullablePostApikeyDelete200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostApikeyDelete200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


