/*
Phishing Hunter API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phishing_hunter

import (
	"encoding/json"
)

// checks if the GetApikeys200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetApikeys200Response{}

// GetApikeys200Response struct for GetApikeys200Response
type GetApikeys200Response struct {
	ApiKeys *GetApikeys200ResponseApiKeys `json:"api_keys,omitempty"`
}

// NewGetApikeys200Response instantiates a new GetApikeys200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetApikeys200Response() *GetApikeys200Response {
	this := GetApikeys200Response{}
	return &this
}

// NewGetApikeys200ResponseWithDefaults instantiates a new GetApikeys200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetApikeys200ResponseWithDefaults() *GetApikeys200Response {
	this := GetApikeys200Response{}
	return &this
}

// GetApiKeys returns the ApiKeys field value if set, zero value otherwise.
func (o *GetApikeys200Response) GetApiKeys() GetApikeys200ResponseApiKeys {
	if o == nil || isNil(o.ApiKeys) {
		var ret GetApikeys200ResponseApiKeys
		return ret
	}
	return *o.ApiKeys
}

// GetApiKeysOk returns a tuple with the ApiKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApikeys200Response) GetApiKeysOk() (*GetApikeys200ResponseApiKeys, bool) {
	if o == nil || isNil(o.ApiKeys) {
		return nil, false
	}
	return o.ApiKeys, true
}

// HasApiKeys returns a boolean if a field has been set.
func (o *GetApikeys200Response) HasApiKeys() bool {
	if o != nil && !isNil(o.ApiKeys) {
		return true
	}

	return false
}

// SetApiKeys gets a reference to the given GetApikeys200ResponseApiKeys and assigns it to the ApiKeys field.
func (o *GetApikeys200Response) SetApiKeys(v GetApikeys200ResponseApiKeys) {
	o.ApiKeys = &v
}

func (o GetApikeys200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetApikeys200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ApiKeys) {
		toSerialize["api_keys"] = o.ApiKeys
	}
	return toSerialize, nil
}

type NullableGetApikeys200Response struct {
	value *GetApikeys200Response
	isSet bool
}

func (v NullableGetApikeys200Response) Get() *GetApikeys200Response {
	return v.value
}

func (v *NullableGetApikeys200Response) Set(val *GetApikeys200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetApikeys200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetApikeys200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetApikeys200Response(val *GetApikeys200Response) *NullableGetApikeys200Response {
	return &NullableGetApikeys200Response{value: val, isSet: true}
}

func (v NullableGetApikeys200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetApikeys200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


