/*
Phishing Hunter API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phishing_hunter

import (
	"encoding/json"
)

// checks if the GetHunting200ResponseKeywords type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetHunting200ResponseKeywords{}

// GetHunting200ResponseKeywords struct for GetHunting200ResponseKeywords
type GetHunting200ResponseKeywords struct {
	Domain []string `json:"domain,omitempty"`
	Dom []string `json:"dom,omitempty"`
}

// NewGetHunting200ResponseKeywords instantiates a new GetHunting200ResponseKeywords object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetHunting200ResponseKeywords() *GetHunting200ResponseKeywords {
	this := GetHunting200ResponseKeywords{}
	return &this
}

// NewGetHunting200ResponseKeywordsWithDefaults instantiates a new GetHunting200ResponseKeywords object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetHunting200ResponseKeywordsWithDefaults() *GetHunting200ResponseKeywords {
	this := GetHunting200ResponseKeywords{}
	return &this
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *GetHunting200ResponseKeywords) GetDomain() []string {
	if o == nil || isNil(o.Domain) {
		var ret []string
		return ret
	}
	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHunting200ResponseKeywords) GetDomainOk() ([]string, bool) {
	if o == nil || isNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *GetHunting200ResponseKeywords) HasDomain() bool {
	if o != nil && !isNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given []string and assigns it to the Domain field.
func (o *GetHunting200ResponseKeywords) SetDomain(v []string) {
	o.Domain = v
}

// GetDom returns the Dom field value if set, zero value otherwise.
func (o *GetHunting200ResponseKeywords) GetDom() []string {
	if o == nil || isNil(o.Dom) {
		var ret []string
		return ret
	}
	return o.Dom
}

// GetDomOk returns a tuple with the Dom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHunting200ResponseKeywords) GetDomOk() ([]string, bool) {
	if o == nil || isNil(o.Dom) {
		return nil, false
	}
	return o.Dom, true
}

// HasDom returns a boolean if a field has been set.
func (o *GetHunting200ResponseKeywords) HasDom() bool {
	if o != nil && !isNil(o.Dom) {
		return true
	}

	return false
}

// SetDom gets a reference to the given []string and assigns it to the Dom field.
func (o *GetHunting200ResponseKeywords) SetDom(v []string) {
	o.Dom = v
}

func (o GetHunting200ResponseKeywords) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetHunting200ResponseKeywords) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !isNil(o.Dom) {
		toSerialize["dom"] = o.Dom
	}
	return toSerialize, nil
}

type NullableGetHunting200ResponseKeywords struct {
	value *GetHunting200ResponseKeywords
	isSet bool
}

func (v NullableGetHunting200ResponseKeywords) Get() *GetHunting200ResponseKeywords {
	return v.value
}

func (v *NullableGetHunting200ResponseKeywords) Set(val *GetHunting200ResponseKeywords) {
	v.value = val
	v.isSet = true
}

func (v NullableGetHunting200ResponseKeywords) IsSet() bool {
	return v.isSet
}

func (v *NullableGetHunting200ResponseKeywords) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetHunting200ResponseKeywords(val *GetHunting200ResponseKeywords) *NullableGetHunting200ResponseKeywords {
	return &NullableGetHunting200ResponseKeywords{value: val, isSet: true}
}

func (v NullableGetHunting200ResponseKeywords) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetHunting200ResponseKeywords) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


