/*
Phishing Hunter API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phishing_hunter

import (
	"encoding/json"
)

// checks if the GetScanner200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetScanner200Response{}

// GetScanner200Response struct for GetScanner200Response
type GetScanner200Response struct {
	Domains []string `json:"domains,omitempty"`
}

// NewGetScanner200Response instantiates a new GetScanner200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetScanner200Response() *GetScanner200Response {
	this := GetScanner200Response{}
	return &this
}

// NewGetScanner200ResponseWithDefaults instantiates a new GetScanner200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetScanner200ResponseWithDefaults() *GetScanner200Response {
	this := GetScanner200Response{}
	return &this
}

// GetDomains returns the Domains field value if set, zero value otherwise.
func (o *GetScanner200Response) GetDomains() []string {
	if o == nil || isNil(o.Domains) {
		var ret []string
		return ret
	}
	return o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetScanner200Response) GetDomainsOk() ([]string, bool) {
	if o == nil || isNil(o.Domains) {
		return nil, false
	}
	return o.Domains, true
}

// HasDomains returns a boolean if a field has been set.
func (o *GetScanner200Response) HasDomains() bool {
	if o != nil && !isNil(o.Domains) {
		return true
	}

	return false
}

// SetDomains gets a reference to the given []string and assigns it to the Domains field.
func (o *GetScanner200Response) SetDomains(v []string) {
	o.Domains = v
}

func (o GetScanner200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetScanner200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Domains) {
		toSerialize["domains"] = o.Domains
	}
	return toSerialize, nil
}

type NullableGetScanner200Response struct {
	value *GetScanner200Response
	isSet bool
}

func (v NullableGetScanner200Response) Get() *GetScanner200Response {
	return v.value
}

func (v *NullableGetScanner200Response) Set(val *GetScanner200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetScanner200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetScanner200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetScanner200Response(val *GetScanner200Response) *NullableGetScanner200Response {
	return &NullableGetScanner200Response{value: val, isSet: true}
}

func (v NullableGetScanner200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetScanner200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


