/*
Phishing Hunter API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phishing_hunter

import (
	"encoding/json"
)

// checks if the GetUsersInfo200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUsersInfo200Response{}

// GetUsersInfo200Response struct for GetUsersInfo200Response
type GetUsersInfo200Response struct {
	Quota *GetUsersInfo200ResponseQuota `json:"quota,omitempty"`
	UserPlan *string `json:"user_plan,omitempty"`
}

// NewGetUsersInfo200Response instantiates a new GetUsersInfo200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUsersInfo200Response() *GetUsersInfo200Response {
	this := GetUsersInfo200Response{}
	return &this
}

// NewGetUsersInfo200ResponseWithDefaults instantiates a new GetUsersInfo200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUsersInfo200ResponseWithDefaults() *GetUsersInfo200Response {
	this := GetUsersInfo200Response{}
	return &this
}

// GetQuota returns the Quota field value if set, zero value otherwise.
func (o *GetUsersInfo200Response) GetQuota() GetUsersInfo200ResponseQuota {
	if o == nil || isNil(o.Quota) {
		var ret GetUsersInfo200ResponseQuota
		return ret
	}
	return *o.Quota
}

// GetQuotaOk returns a tuple with the Quota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsersInfo200Response) GetQuotaOk() (*GetUsersInfo200ResponseQuota, bool) {
	if o == nil || isNil(o.Quota) {
		return nil, false
	}
	return o.Quota, true
}

// HasQuota returns a boolean if a field has been set.
func (o *GetUsersInfo200Response) HasQuota() bool {
	if o != nil && !isNil(o.Quota) {
		return true
	}

	return false
}

// SetQuota gets a reference to the given GetUsersInfo200ResponseQuota and assigns it to the Quota field.
func (o *GetUsersInfo200Response) SetQuota(v GetUsersInfo200ResponseQuota) {
	o.Quota = &v
}

// GetUserPlan returns the UserPlan field value if set, zero value otherwise.
func (o *GetUsersInfo200Response) GetUserPlan() string {
	if o == nil || isNil(o.UserPlan) {
		var ret string
		return ret
	}
	return *o.UserPlan
}

// GetUserPlanOk returns a tuple with the UserPlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsersInfo200Response) GetUserPlanOk() (*string, bool) {
	if o == nil || isNil(o.UserPlan) {
		return nil, false
	}
	return o.UserPlan, true
}

// HasUserPlan returns a boolean if a field has been set.
func (o *GetUsersInfo200Response) HasUserPlan() bool {
	if o != nil && !isNil(o.UserPlan) {
		return true
	}

	return false
}

// SetUserPlan gets a reference to the given string and assigns it to the UserPlan field.
func (o *GetUsersInfo200Response) SetUserPlan(v string) {
	o.UserPlan = &v
}

func (o GetUsersInfo200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUsersInfo200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Quota) {
		toSerialize["quota"] = o.Quota
	}
	if !isNil(o.UserPlan) {
		toSerialize["user_plan"] = o.UserPlan
	}
	return toSerialize, nil
}

type NullableGetUsersInfo200Response struct {
	value *GetUsersInfo200Response
	isSet bool
}

func (v NullableGetUsersInfo200Response) Get() *GetUsersInfo200Response {
	return v.value
}

func (v *NullableGetUsersInfo200Response) Set(val *GetUsersInfo200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUsersInfo200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUsersInfo200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUsersInfo200Response(val *GetUsersInfo200Response) *NullableGetUsersInfo200Response {
	return &NullableGetUsersInfo200Response{value: val, isSet: true}
}

func (v NullableGetUsersInfo200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUsersInfo200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


