/*
Phishing Hunter API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phishing_hunter

import (
	"encoding/json"
)

// checks if the PostScannerAdd200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostScannerAdd200Response{}

// PostScannerAdd200Response struct for PostScannerAdd200Response
type PostScannerAdd200Response struct {
	Result *bool `json:"result,omitempty"`
}

// NewPostScannerAdd200Response instantiates a new PostScannerAdd200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostScannerAdd200Response() *PostScannerAdd200Response {
	this := PostScannerAdd200Response{}
	return &this
}

// NewPostScannerAdd200ResponseWithDefaults instantiates a new PostScannerAdd200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostScannerAdd200ResponseWithDefaults() *PostScannerAdd200Response {
	this := PostScannerAdd200Response{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *PostScannerAdd200Response) GetResult() bool {
	if o == nil || isNil(o.Result) {
		var ret bool
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostScannerAdd200Response) GetResultOk() (*bool, bool) {
	if o == nil || isNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *PostScannerAdd200Response) HasResult() bool {
	if o != nil && !isNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given bool and assigns it to the Result field.
func (o *PostScannerAdd200Response) SetResult(v bool) {
	o.Result = &v
}

func (o PostScannerAdd200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostScannerAdd200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullablePostScannerAdd200Response struct {
	value *PostScannerAdd200Response
	isSet bool
}

func (v NullablePostScannerAdd200Response) Get() *PostScannerAdd200Response {
	return v.value
}

func (v *NullablePostScannerAdd200Response) Set(val *PostScannerAdd200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostScannerAdd200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostScannerAdd200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostScannerAdd200Response(val *PostScannerAdd200Response) *NullablePostScannerAdd200Response {
	return &NullablePostScannerAdd200Response{value: val, isSet: true}
}

func (v NullablePostScannerAdd200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostScannerAdd200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


