/*
Phishing Hunter API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package phishing_hunter

import (
	"encoding/json"
)

// checks if the PostScannerAddRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostScannerAddRequest{}

// PostScannerAddRequest struct for PostScannerAddRequest
type PostScannerAddRequest struct {
	Domain *string `json:"domain,omitempty"`
}

// NewPostScannerAddRequest instantiates a new PostScannerAddRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostScannerAddRequest() *PostScannerAddRequest {
	this := PostScannerAddRequest{}
	return &this
}

// NewPostScannerAddRequestWithDefaults instantiates a new PostScannerAddRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostScannerAddRequestWithDefaults() *PostScannerAddRequest {
	this := PostScannerAddRequest{}
	return &this
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *PostScannerAddRequest) GetDomain() string {
	if o == nil || isNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostScannerAddRequest) GetDomainOk() (*string, bool) {
	if o == nil || isNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *PostScannerAddRequest) HasDomain() bool {
	if o != nil && !isNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *PostScannerAddRequest) SetDomain(v string) {
	o.Domain = &v
}

func (o PostScannerAddRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostScannerAddRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	return toSerialize, nil
}

type NullablePostScannerAddRequest struct {
	value *PostScannerAddRequest
	isSet bool
}

func (v NullablePostScannerAddRequest) Get() *PostScannerAddRequest {
	return v.value
}

func (v *NullablePostScannerAddRequest) Set(val *PostScannerAddRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostScannerAddRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostScannerAddRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostScannerAddRequest(val *PostScannerAddRequest) *NullablePostScannerAddRequest {
	return &NullablePostScannerAddRequest{value: val, isSet: true}
}

func (v NullablePostScannerAddRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostScannerAddRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


