/**
 * Phishing Hunter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PhishingHunterApi);
  }
}(this, function(expect, PhishingHunterApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PhishingHunterApi.PostObservationAddRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PostObservationAddRequest', function() {
    it('should create an instance of PostObservationAddRequest', function() {
      // uncomment below and update the code to test PostObservationAddRequest
      //var instance = new PhishingHunterApi.PostObservationAddRequest();
      //expect(instance).to.be.a(PhishingHunterApi.PostObservationAddRequest);
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new PhishingHunterApi.PostObservationAddRequest();
      //expect(instance).to.be();
    });

    it('should have the property interval (base name: "interval")', function() {
      // uncomment below and update the code to test the property interval
      //var instance = new PhishingHunterApi.PostObservationAddRequest();
      //expect(instance).to.be();
    });

    it('should have the property period (base name: "period")', function() {
      // uncomment below and update the code to test the property period
      //var instance = new PhishingHunterApi.PostObservationAddRequest();
      //expect(instance).to.be();
    });

    it('should have the property comment (base name: "comment")', function() {
      // uncomment below and update the code to test the property comment
      //var instance = new PhishingHunterApi.PostObservationAddRequest();
      //expect(instance).to.be();
    });

    it('should have the property expire (base name: "expire")', function() {
      // uncomment below and update the code to test the property expire
      //var instance = new PhishingHunterApi.PostObservationAddRequest();
      //expect(instance).to.be();
    });

    it('should have the property apiConfig (base name: "api_config")', function() {
      // uncomment below and update the code to test the property apiConfig
      //var instance = new PhishingHunterApi.PostObservationAddRequest();
      //expect(instance).to.be();
    });

  });

}));
