/**
 * Phishing Hunter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PhishingHunterApi);
  }
}(this, function(expect, PhishingHunterApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PhishingHunterApi.PostObservationAddRequestApiConfigUrlscan();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PostObservationAddRequestApiConfigUrlscan', function() {
    it('should create an instance of PostObservationAddRequestApiConfigUrlscan', function() {
      // uncomment below and update the code to test PostObservationAddRequestApiConfigUrlscan
      //var instance = new PhishingHunterApi.PostObservationAddRequestApiConfigUrlscan();
      //expect(instance).to.be.a(PhishingHunterApi.PostObservationAddRequestApiConfigUrlscan);
    });

    it('should have the property visibility (base name: "visibility")', function() {
      // uncomment below and update the code to test the property visibility
      //var instance = new PhishingHunterApi.PostObservationAddRequestApiConfigUrlscan();
      //expect(instance).to.be();
    });

  });

}));
